spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/testdb'
    username: pguser
    password: passwd123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true

logging:
  file:
    name: "/logs/ria-rating-report.log"

ria-rating-report:
  scheduler:
    enable: true
    cron: '0 */30 * * * ?' # every 30 minutes